apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
    environment: dev
spec:
  type: NodePort
  selector:
    app: wordpress
    environment: dev
  ports:
    - protocol: TCP
      port: 82
      targetPort: 82
      nodePort: 32001