apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-svc
  labels:
    app: grafana
    environment: dev
spec:
  type: NodePort
  selector:
    app: grafana
    environment: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32600
