apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus-svc
  labels:
    app: prometheus
    environment: dev
spec:
  type: NodePort
  selector:
    app: prometheus
    environment: dev
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32500
