apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: prometheus-pvc
  labels:
    app: prometheus
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
